-- Run this in Supabase SQL editor.

create table if not exists public.booking_requests (
  id bigint generated by default as identity primary key,
  active boolean not null default true,
  guest_name text not null,
  guest_email text not null,
  guest_phone text not null,
  special_request text not null default '',
  booking_url text not null,
  guests integer not null default 2,
  time_text text not null default '8:00 PM',
  fallback_start text not null default '8:00 PM',
  fallback_end text not null default '10:00 PM',
  slot_interval_minutes integer not null default 15,
  timezone text not null default 'Asia/Kolkata',
  auto_confirm boolean not null default true,
  headless boolean not null default true,
  last_run_date date,
  last_status text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.booking_runs (
  id bigint generated by default as identity primary key,
  booking_request_id bigint not null references public.booking_requests(id) on delete cascade,
  run_date date not null,
  status text not null,
  message text not null default '',
  created_at timestamptz not null default now()
);

alter table public.booking_requests enable row level security;
alter table public.booking_runs enable row level security;

-- Public form can only create booking requests.
drop policy if exists "anon_insert_booking_requests" on public.booking_requests;
create policy "anon_insert_booking_requests"
on public.booking_requests
for insert
to anon
with check (true);

-- No public read/update/delete.
drop policy if exists "anon_no_read_booking_requests" on public.booking_requests;
create policy "anon_no_read_booking_requests"
on public.booking_requests
for select
to anon
using (false);

drop policy if exists "anon_no_read_booking_runs" on public.booking_runs;
create policy "anon_no_read_booking_runs"
on public.booking_runs
for select
to anon
using (false);
