from pathlib import Path


def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def run() -> None:
    out_path = Path(".booking.env")
    print("Booking config setup (saved to .booking.env)")
    print("Press Enter to accept defaults.")

    values = {
        "BOOKING_URL": ask(
            "Booking URL",
            "https://www.tablecheck.com/en/pizza-4ps-in-indiranagar/reserve/message",
        ),
        "GUESTS": ask("Guests", "2"),
        "TIME_TEXT": ask("Preferred start time", "8:00 PM"),
        "FALLBACK_START": ask("Fallback start time", "8:00 PM"),
        "FALLBACK_END": ask("Fallback end time", "10:00 PM"),
        "SLOT_INTERVAL_MINUTES": ask("Slot interval minutes", "15"),
        "GUEST_NAME": ask("Guest full name", "Tanay Gupta"),
        "GUEST_EMAIL": ask("Guest email", "tanaygupta2000@gmail.com"),
        "GUEST_PHONE": ask("Guest phone", "+91 9057222901"),
        "SPECIAL_REQUEST": ask("Special request (optional)", ""),
        "AUTO_CONFIRM": ask("Auto confirm booking (true/false)", "true"),
        "HEADLESS": ask("Run headless (true/false)", "true"),
        "TIMEZONE": ask("Timezone", "Asia/Kolkata"),
        "SAVE_DEBUG_PAGES": ask("Save debug pages (true/false)", "true"),
        "DEBUG_DIR": ask("Debug output dir", "debug-pages"),
    }

    lines = [
        "# Generated by setup_booking_config.py",
        "# Used automatically by book_reservation.py (via BOOKING_CONFIG_FILE or .booking.env)",
    ]
    for key, value in values.items():
        lines.append(f"{key}={quote(value)}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Saved config to {out_path.resolve()}")


if __name__ == "__main__":
    run()
